# generated by datamodel-codegen:
#   filename:  activity-log-alert-sample-payload.json
#   timestamp: 2021-08-28T01:29:16+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class AnyPayloadInput(BaseModel):
    __root__: Any
