# generated by datamodel-codegen:
#   filename:  azure-monitor-common-alert-schema.json
#   timestamp: 2021-08-28T02:11:19+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class Essentials(BaseModel):
    alertId: str
    alertRule: str
    severity: str
    signalType: str
    monitorCondition: str
    monitoringService: str
    alertTargetIDs: List[str]
    configurationItems: List[str]
    originAlertId: str
    firedDateTime: str
    resolvedDateTime: str
    description: str
    essentialsVersion: str
    alertContextVersion: str


class Dimension(BaseModel):
    name: str
    value: str


class AllOfItem(BaseModel):
    metricName: str
    metricNamespace: str
    operator: str
    threshold: str
    timeAggregation: str
    dimensions: List[Dimension]
    metricValue: float


class Condition(BaseModel):
    windowSize: str
    allOf: List[AllOfItem]


class AlertContext(BaseModel):
    properties: Any
    conditionType: str
    condition: Condition


class Data(BaseModel):
    essentials: Essentials
    alertContext: AlertContext


class Model(BaseModel):
    schemaId: str
    data: Data
